In [1]:
using SSM
using Random
using Distributions
using Plots
using LinearAlgebra
using CSV
using DataFrames

In [2]:
robert = CSV.read("/Users/ryansenne/Downloads/robert_deltaflash_choice.csv", DataFrame)
# extract variables
choice = Array{Float64}(robert.choice)
delta_flashes = reshape(Array{Float64}(robert.delta_flashes), length(choice), 1)

18667×1 Matrix{Float64}:
 -10.0
  20.0
  -6.0
  -3.0
   4.0
   4.0
  -2.0
   5.0
   5.0
 -10.0
   ⋮
  -4.0
   4.0
  -2.0
   3.0
   6.0
   2.0
  -6.0
  -5.0
  -6.0

In [3]:
# create data from a PoissonRegression model

X = randn(length(choice), 1)
X = [ones(length(choice)) X]

β = [1.0, 2.0]
μ = X * β

y = rand.(Poisson.(exp.(μ)))

# create a PoissonRegression model
model = PoissonRegression(include_intercept = false)
model.β = zeros(2)
# fit the model
fit!(model, X, y)

2-element Vector{Float64}:
 1.0018353112281189
 1.9981958808653864

In [7]:
using ForwardDiff
# create an objective function to look at the grad of the loglikelihood
obj = β -> -SSM.loglikelihood(PoissonRegression(β, false, 0.0), X, y)

grad = ForwardDiff.gradient(obj, [0.0, 0.0])


2-element Vector{Float64}:
 -360373.0
 -744820.419934163

In [5]:
SSM.gradient!([0.0, 0.0], model, X, y)

2-element Vector{Float64}:
 -360373.0
 -744820.4199341631