In [1]:
using Pkg
Pkg.activate("/Users/ryansenne/Documents/Github/ssm_julia/")


  Activating project at `\Users\ryansenne\Documents\Github\ssm_julia`


In [2]:
include("/Users/ryansenne/Documents/Github/ssm_julia/src/SSM.jl")
using Random
using .SSM
using Distributions
using Plots
using LinearAlgebra
using ForwardDiff
using StatsFuns
using Optim

In [3]:
# generate synthetic data
Random.seed!(123)

# set parameters
n = 1000
β = [0.1, 0.9]

# generate data
X = hcat(ones(n), randn(n, 1))

p = logistic.(X * β)
y = rand.(Bernoulli.(p));

logreg = SSM.BernoulliRegression()
SSM.fit!(logreg, reshape(X[:, 2], length(y), 1), y)

2-element Vector{Float64}:
 -0.16475074895339847
  0.9130020117197616

In [4]:
model = SSM.SwitchingBernoulliRegression(;K=2, λ=0.1)
SSM.fit!(model, reshape(X[:, 2], length(y), 1), y, 10)

(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)


In [5]:
# synthetic poisson regression data
Random.seed!(123)

# set parameters
n = 100
β = [0.1, 0.9]
# generate data

X = hcat(ones(n), randn(n, 1))
λ = exp.(X * β)

y = rand.(Poisson.(λ))

poisreg = SSM.PoissonRegression()
SSM.fit!(poisreg, reshape(X[:, 2], length(y), 1), y)

2-element Vector{Float64}:
 0.17487914508365066
 0.947349969129698

In [6]:
model = SSM.SwitchingPoissonRegression(;K=2, λ=0.1)
fit!(model, reshape(X[:, 2], length(y), 1), y)

Log-Likelihood at iter 1: -156.45428974993172
Log-Likelihood at iter 2: -135.25621720804358
Log-Likelihood at iter 3: -134.16285096688912
Log-Likelihood at iter 4: -133.83642369645605
Log-Likelihood at iter 5: -133.7079105961072
Log-Likelihood at iter 6: -133.64984042864145
Log-Likelihood at iter 7: -133.62099977477772
Log-Likelihood at iter 8: -133.6058209832856
Log-Likelihood at iter 9: -133.5975567520573
Log-Likelihood at iter 10: -133.59296693195853
Log-Likelihood at iter 11: -133.59038555167996
Log-Likelihood at iter 12: -133.58891948685175
Log-Likelihood at iter 13: -133.58807819216423
Log-Likelihood at iter 14: -133.58758851551048
Log-Likelihood at iter 15: -133.58729717669178
Log-Likelihood at iter 16: -133.587117786321
Log-Likelihood at iter 17: -133.5870015358344
Log-Likelihood at iter 18: -133.58692081297323
Log-Likelihood at iter 19: -133.58685998772486
Log-Likelihood at iter 20: -133.58681021236723
Log-Likelihood at iter 21: -133.58676648071955
Log-Likelihood at iter 22: -

101-element Vector{Float64}:
  -Inf
 -156.45428974993172
 -135.25621720804358
 -134.16285096688912
 -133.83642369645605
 -133.7079105961072
 -133.64984042864145
 -133.62099977477772
 -133.6058209832856
 -133.5975567520573
    ⋮
 -133.58367065036043
 -133.58362956826656
 -133.5835888251289
 -133.5835484279308
 -133.58350838327405
 -133.58346869737287
 -133.58342937616737
 -133.58339042503604
 -133.58335184922993