In [1]:
using SSM
using Random
using Distributions
using Plots
using LinearAlgebra
using CSV
using DataFrames

In [2]:
robert = CSV.read("/Users/ryansenne/Downloads/robert_deltaflash_choice.csv", DataFrame)
# extract variables
choice = Array{Float64}(robert.choice)
delta_flashes = reshape(Array{Float64}(robert.delta_flashes), length(choice), 1)

18667×1 Matrix{Float64}:
 -10.0
  20.0
  -6.0
  -3.0
   4.0
   4.0
  -2.0
   5.0
   5.0
 -10.0
   ⋮
  -4.0
   4.0
  -2.0
   3.0
   6.0
   2.0
  -6.0
  -5.0
  -6.0

In [8]:
# fit a switching logistic regression model
model = SSM.SwitchingBernoulliRegression(;K=3, λ=0.1)
SSM.initialize_regression!(model, delta_flashes, choice)
# fit!(model, delta_flashes, choice)

18667×3 Matrix{Float64}:
 -9793.6       -9793.51     -9793.16
 -9793.72      -9793.36     -9792.96
 -9793.37      -9792.92     -9792.79
 -9792.64      -9792.67     -9792.71
 -9792.68      -9792.45     -9792.7
 -9792.11      -9792.82     -9793.16
 -9791.54      -9791.46     -9791.45
 -9791.39      -9791.51     -9791.47
 -9791.7       -9791.1      -9791.37
 -9790.57      -9791.37     -9792.21
     ⋮                      
    -4.7746       -4.54137     -4.79821
    -4.20021      -4.90941     -5.26082
    -3.56221      -3.55783     -3.55379
    -3.54382      -3.44578     -3.49848
    -3.31011      -3.49776     -3.59494
    -3.60416      -2.95849     -3.44717
    -2.35421      -3.24924     -6.12873
    -0.728938     -1.61449     -3.98373
     0.0           0.0          0.0

In [11]:
fit!(model, delta_flashes, choice, 250)

Log-Likelihood at iter 1: -9998.3019669076
Log-Likelihood at iter 2: -8487.316309102514
Log-Likelihood at iter 3: -8415.937926862316
Log-Likelihood at iter 4: -8351.25036633229
Log-Likelihood at iter 5: -8270.249165482313
Log-Likelihood at iter 6: -8184.562145797018
Log-Likelihood at iter 7: -8105.217184240914
Log-Likelihood at iter 8: -8028.624598848068
Log-Likelihood at iter 9: -7946.779314999303
Log-Likelihood at iter 10: -7852.8302849470765
Log-Likelihood at iter 11: -7750.697936297667
Log-Likelihood at iter 12: -7655.645776790163
Log-Likelihood at iter 13: -7583.751008394669
Log-Likelihood at iter 14: -7537.924651407812
Log-Likelihood at iter 15: -7510.371018077398
Log-Likelihood at iter 16: -7493.722564276985
Log-Likelihood at iter 17: -7483.520967704468
Log-Likelihood at iter 18: -7476.907676344374
Log-Likelihood at iter 19: -7472.171857524559
Log-Likelihood at iter 20: -7468.380469639836
Log-Likelihood at iter 21: -7465.03041427334
Log-Likelihood at iter 22: -7461.851355047644


251-element Vector{Float64}:
   -Inf
 -9998.3019669076
 -8487.316309102514
 -8415.937926862316
 -8351.25036633229
 -8270.249165482313
 -8184.562145797018
 -8105.217184240914
 -8028.624598848068
 -7946.779314999303
     ⋮
 -7433.030645148455
 -7433.030607489515
 -7433.030570574246
 -7433.030534371202
 -7433.030498880036
 -7433.030464075424
 -7433.030429948442
 -7433.030396479832
 -7433.030363665157

In [12]:
model

SwitchingBernoulliRegression([0.732679299272282 0.0587719983752107 0.2085487023525089; 0.010216349173853233 0.9897773416694946 6.309156662092262e-6; 0.08242044958611827 0.0013645533538268122 0.9162149970600127], RegressionEmissions[RegressionEmissions(BernoulliRegression([-6.611099956008394, -0.28067485714859386], true, 0.1)), RegressionEmissions(BernoulliRegression([0.33977111398192567, 0.4216687258137248], true, 0.1)), RegressionEmissions(BernoulliRegression([3.9645868093862355, 0.620452202414644], true, 0.1))], [0.0, 1.0, 2.71624062847257e-89], 3, 0.1)

In [59]:
lls = [SSM.loglikelihood(model.B[1], cat(1, delta_flashes[i], dims=1), choice[i]) for i in 1:length(choice)]

18667-element Vector{Float64}:
  -0.0012927855361969988
 -13.077533502000415
  -4.037725729231072
  -2.1685699835215084
  -2.6307649145945993
  -2.6307649145945993
  -0.22249287312110552
  -3.253034630617199
  -3.253034630617199
  -6.65160238135729
   ⋮
  -0.06474564260193125
  -2.6307649145945993
  -0.22249287312110552
  -2.038013781508877
  -3.891824800838763
  -1.4948060549241928
  -4.037725729231072
  -0.03406727311083181
  -0.017794934225943478