In [1]:
using Pkg
Pkg.activate("/Users/ryansenne/Documents/Github/SSM/")
# Pkg.activate("/home/ryansenne/PycharmProjects/ssm_julia/")

  Activating project at `\Users\ryansenne\Documents\Github\SSM`

In [2]:
include("/Users/ryansenne/Documents/Github/SSM//src/SSM.jl")
# include("/home/ryansenne/PycharmProjects/ssm_julia/src/SSM.jl")
using Random
using .SSM
using Distributions

### Gaussian GLM Example

In [1]:
# Fit a Gaussian GLM
# Generate some synthetic data
X = rand(10000, 3);  # 100 samples, 3 features;
# Add a column of ones to represent the intercept term
X_concat = hcat(ones(10000), X)
β = [2, 3, -4, 5]
y = X_concat * β + rand(Normal(0, 1), 10000)

# define a GLM
glm = GaussianRegression(X, y)
fit!(glm, 1000)

UndefVarError: UndefVarError: `Normal` not defined

### Poisson GLM Example

In [4]:
# Fit a Poisson GLM
# Generate some synthetic data
X = rand(10000, 3);  # 100 samples, 3 features;
# Add a column of ones to represent the intercept term
X_concat = hcat(ones(10000), X)
β = [2, 3, -4, 5]

# Generate some synthetic data
y = Vector{Float64}(rand.(Poisson.(exp.(X_concat * β))))

# define a GLM
glm = PoissonRegression(X, y)
fit!(glm, 1000)


4-element Vector{Float64}:
  1.9972876910665238
  3.0018761978448465
 -4.001568346180793
  5.002617122785103

### Binomial GLM Example (i.e. logistic regression)

In [3]:
# sigmoid function
function sigmoid(x)
    return 1 / (1 + exp(-x))
end

# Fit a Binomial GLM
# Generate some synthetic data
X = rand(10000, 3); # 1000 samples, 3 features;
# Add a column of ones to represent the intercept term
X_concat = hcat(ones(10000), X)
β = [2, 3, -4, 5]

# Generate some synthetic data
y = Vector{Float64}(rand.(Binomial.(1, sigmoid.(X_concat * β))))

# define a GLM
glm = BinomialRegression(X, y)
fit!(glm, 1000)

4-element Vector{Float64}:
  1.8285295895751685
  3.0115236069793356
 -3.778705515037161
  5.156155128038023

# Autoregressive Model

In [3]:
# simulate AR(1) model
init_val = 0.0
phi = 0.9
sigma = 1.0
T = 1000
y = Vector{Float64}(undef, T)
y[1] = init_val
for t in 2:T
    y[t] = phi * y[t-1] + rand(Normal(0, sigma))
end

ar_1 = Autoregression(y, 1)
fit!(ar_1)

0.9538958584342558

In [3]:
# try out markov glm

# Generate synthetic data from two distinct regimes
X = rand(100, 3); # 1000 samples, 3 features;
# Add a column of ones to represent the intercept term
X_concat = hcat(ones(100), X)
β₁ = [-20, -30, -40, 50]
β₂ = [6, 7, 8, -9]

# Generate some synthetic data
y₁ = X_concat * β₁ + rand(Normal(0, 0.1), 100)
y₂ = X_concat * β₂ + rand(Normal(0, 1), 100)

# concatenate X1 and X2
x = vcat(X, X)

# concatenate y1 and y2
y = vcat(y₁, y₂)

# define a Gaussian HMMGLM
glm = GaussianMarkovRegression(y, x, 2)

MarkovRegressionEM(glm)

Iteration: 1, Log-likelihood: -895.1450879718143
Iteration: 2, Log-likelihood: -890.9349305035108
Iteration: 3, Log-likelihood: -886.8866345435962
Iteration: 4, Log-likelihood: -882.240720318679
Iteration: 5, Log-likelihood: -876.693573819367
Iteration: 6, Log-likelihood: -869.8574676480326
Iteration: 7, Log-likelihood: -862.0109276657228
Iteration: 8, Log-likelihood: -855.1293694624018
Iteration: 9, Log-likelihood: -850.6397956737135
Iteration: 10, Log-likelihood: -847.7767480980992
Iteration: 11, Log-likelihood: -845.7570137848197
Iteration: 12, Log-likelihood: -844.2796062348233
Iteration: 13, Log-likelihood: -843.2557914172486
Iteration: 14, Log-likelihood: -842.6234834088976
Iteration: 15, Log-likelihood: -842.2787370105883
Iteration: 16, Log-likelihood: -842.1069509981659
Iteration: 17, Log-likelihood: -842.0251428151403
Convergence reached at iteration 17


Initial Variance: 

[987.252905003522, 36.39460385625851]
Initial Transition Matrix: 

[0.9433962264150944 0.05660377358490566; 0.07526881720430108 0.9247311827956989]
Initial Mixing Coefficients: [3.330266527986876e-9, 0.9999999966697333]


Log-likelihood at iteration 1: -165822.57712092478
Log-likelihood at iteration 2: -165666.49380444828
Log-likelihood at iteration 3: -165389.53983234605
Log-likelihood at iteration 4: -165199.1273623775
Log-likelihood at iteration 5: 

-165198.68820856334
Log-likelihood at iteration 6: -165198.66088873136
Log-likelihood at iteration 7: -165198.658386102
Log-likelihood at iteration 8: -165198.65814964593
Log-likelihood at iteration 9: -165198.65812723813
Log-likelihood at iteration 10: -165198.65812511474
Log-likelihood at iteration 11: -165198.6581249099


In [4]:
glm.σ²

2-element Vector{Float64}:
 987.0693985987194
 918.9063057428358

In [4]:
glm.B[2].regression_model.β

4-element Vector{Float64}:
  7.037935604057497
  5.403145553763766
  7.412466590865421
 -8.508343109235135