In [1]:
using Pkg
Pkg.activate("/Users/ryansenne/Documents/Github/SSM/")
# Pkg.activate("/home/ryansenne/PycharmProjects/ssm_julia/")

  Activating project at `\Users\ryansenne\Documents\Github\SSM`


In [2]:
include("/Users/ryansenne/Documents/Github/SSM//src/SSM.jl")
# include("/home/ryansenne/PycharmProjects/ssm_julia/src/SSM.jl")
using Random
using .SSM
using Distributions
using Plots
using LinearAlgebra
using ForwardDiff
using StatsFuns
using Optim

In [4]:
# generate synthetic data
Random.seed!(123)

# set parameters
n = 100
β = [0.1, 0.9]

# generate data
X = hcat(ones(n), randn(n, 1))

p = logistic.(X * β)
y = rand.(Bernoulli.(p));

logreg = SSM.BernoulliRegression()
SSM.fit!(logreg, reshape(X[:, 2], length(y), 1), y)

2-element Vector{Float64}:
 -0.2254724389883398
  1.1635789534220071

In [6]:
model = SSM.SwitchingBernoulliRegression(;K=2, λ=0.1)
SSM.fit!(model, reshape(X[:, 2], length(y), 1), y)

Log-Likelihood at iter 1: -60.63999840059348
Log-Likelihood at iter 2: -58.716157104346955
Log-Likelihood at iter 3: -58.65914431475913
Log-Likelihood at iter 4: -58.6334069835488
Log-Likelihood at iter 5: -58.621134223960375
Log-Likelihood at iter 6: -58.61466348073864
Log-Likelihood at iter 7: -58.61055306265681
Log-Likelihood at iter 8: -58.60738390190144
Log-Likelihood at iter 9: -58.60462866644438
Log-Likelihood at iter 10: -58.60212085969285
Log-Likelihood at iter 11: -58.599822807315974
Log-Likelihood at iter 12: -58.597731881580245
Log-Likelihood at iter 13: -58.59584712607942
Log-Likelihood at iter 14: -58.59416052827664
Log-Likelihood at iter 15: -58.59265722625968
Log-Likelihood at iter 16: -58.59131815054471
Log-Likelihood at iter 17: -58.59012266091704
Log-Likelihood at iter 18: -58.58905047266244
Log-Likelihood at iter 19: -58.5880828315609
Log-Likelihood at iter 20: -58.58720308597043
Log-Likelihood at iter 21: -58.58639686646999
Log-Likelihood at iter 22: -58.5856520147

101-element Vector{Float64}:
 -Inf
 -60.63999840059348
 -58.716157104346955
 -58.65914431475913
 -58.6334069835488
 -58.621134223960375
 -58.61466348073864
 -58.61055306265681
 -58.60738390190144
 -58.60462866644438
   ⋮
 -58.558901617604405
 -58.55861835016518
 -58.55833709753887
 -58.55805785917444
 -58.557780632262975
 -58.55750541473512
 -58.557232204206876
 -58.55696099769719
 -58.556691792127374

In [9]:
# synthetic poisson regression data
Random.seed!(123)

# set parameters
n = 100
β = [0.1, 0.9]
# generate data

X = hcat(ones(n), randn(n, 1))
λ = exp.(X * β)

y = rand.(Poisson.(λ))

poisreg = SSM.PoissonRegression()
SSM.fit!(poisreg, reshape(X[:, 2], length(y), 1), y)

2-element Vector{Float64}:
 0.17487914508365066
 0.947349969129698