In [1]:
using Pkg
Pkg.activate("/Users/ryansenne/Documents/Github/SSM/")
# Pkg.activate("/home/ryansenne/PycharmProjects/ssm_julia/")

  Activating project at `\Users\ryansenne\Documents\Github\SSM`


In [2]:
include("/Users/ryansenne/Documents/Github/SSM//src/SSM.jl")
# include("/home/ryansenne/PycharmProjects/ssm_julia/src/SSM.jl")
using Random
using .SSM
using Distributions

### Gaussian GLM Example

In [3]:
# Fit a Gaussian GLM
# Generate some synthetic data
X = rand(10000, 3);  # 100 samples, 3 features;
# Add a column of ones to represent the intercept term
X_concat = hcat(ones(10000), X)
β = [2, 3, -4, 5]
y = X_concat * β + rand(Normal(0, 1), 10000)

# define a GLM
glm = GaussianRegression(X, y)
fit!(glm, 1000)

4-element Vector{Float64}:
  1.963508062948609
  3.0472521214354646
 -4.032847152584493
  5.085586252239004

### Poisson GLM Example

In [4]:
# Fit a Poisson GLM
# Generate some synthetic data
X = rand(10000, 3);  # 100 samples, 3 features;
# Add a column of ones to represent the intercept term
X_concat = hcat(ones(10000), X)
β = [2, 3, -4, 5]

# Generate some synthetic data
y = Vector{Float64}(rand.(Poisson.(exp.(X_concat * β))))

# define a GLM
glm = PoissonRegression(X, y)
fit!(glm, 1000)


4-element Vector{Float64}:
  1.9972876910665238
  3.0018761978448465
 -4.001568346180793
  5.002617122785103

### Binomial GLM Example (i.e. logistic regression)

In [3]:
# sigmoid function
function sigmoid(x)
    return 1 / (1 + exp(-x))
end

# Fit a Binomial GLM
# Generate some synthetic data
X = rand(10000, 3); # 1000 samples, 3 features;
# Add a column of ones to represent the intercept term
X_concat = hcat(ones(10000), X)
β = [2, 3, -4, 5]

# Generate some synthetic data
y = Vector{Float64}(rand.(Binomial.(1, sigmoid.(X_concat * β))))

# define a GLM
glm = BinomialRegression(X, y)
fit!(glm, 1000)

4-element Vector{Float64}:
  1.8285295895751685
  3.0115236069793356
 -3.778705515037161
  5.156155128038023

# Autoregressive Model

In [3]:
# simulate AR(1) model
init_val = 0.0
phi = 0.9
sigma = 1.0
T = 1000
y = Vector{Float64}(undef, T)
y[1] = init_val
for t in 2:T
    y[t] = phi * y[t-1] + rand(Normal(0, sigma))
end

ar_1 = Autoregression(y, 1)
fit!(ar_1)

0.9538958584342558

In [3]:
# try out markov glm

# Generate synthetic data from two distinct regimes
X = rand(100, 3); # 1000 samples, 3 features;
# Add a column of ones to represent the intercept term
X_concat = hcat(ones(100), X)
β₁ = [-20, -30, -40, 50]
β₂ = [6, 7, 8, -9]

# Generate some synthetic data
y₁ = X_concat * β₁ + rand(Normal(0, 0.1), 100)
y₂ = X_concat * β₂ + rand(Normal(0, 1), 100)

# concatenate X1 and X2
x = vcat(X, X)

# concatenate y1 and y2
y = vcat(y₁, y₂)

# define a Gaussian HMMGLM
glm = SwitchingGaussianRegression(y, x, 2)

MarkovRegressionEM(glm)

Iteration: 1, Log-likelihood: -908.4401059544339
Iteration: 2, Log-likelihood: -906.5738878276048
Iteration: 3, Log-likelihood: -905.4639984734732
Iteration: 4, Log-likelihood: -904.2764353233149
Iteration: 5, Log-likelihood: -902.8829726080554
Iteration: 6, Log-likelihood: -901.2188366288901
Iteration: 7, Log-likelihood: -899.2175681843619
Iteration: 8, Log-likelihood: -896.8000873473582
Iteration: 9, Log-likelihood: -893.875661914992
Iteration: 10, Log-likelihood: -890.3527225617067
Iteration: 11, Log-likelihood: -886.1607450333303
Iteration: 12, Log-likelihood: -881.2674028585702
Iteration: 13, Log-likelihood: -875.6614840802282
Iteration: 14, Log-likelihood: -869.3606110852567
Iteration: 15, Log-likelihood: -862.5357673685215
Iteration: 16, Log-likelihood: -855.3197555105721
Iteration: 17, Log-likelihood: -847.531382316455
Iteration: 18, Log-likelihood: -840.2504486242824
Iteration: 19, Log-likelihood: -836.3892460724626
Iteration: 20, Log-likelihood: -835.4224818952275
Iteration: 

DomainError: DomainError with -100.61267674568039:
log will only return a complex result if called with a complex argument. Try log(Complex(x)).

In [4]:
glm.σ²

2-element Vector{Float64}:
 NaN
 NaN

In [5]:
glm.B[2].regression_model.β

4-element Vector{Float64}:
 -20.058395420154884
 -28.413295346218813
 -38.62800924981708
  48.29198573140382