In [1]:
using Pkg
Pkg.activate("/Users/ryansenne/Documents/Github/SSM/")
# Pkg.activate("/home/ryansenne/PycharmProjects/ssm_julia/")

  Activating project at `\Users\ryansenne\Documents\Github\SSM`


In [2]:
include("/Users/ryansenne/Documents/Github/SSM//src/SSM.jl")
# include("/home/ryansenne/PycharmProjects/ssm_julia/src/SSM.jl")
using Random
using .SSM
using Distributions
using Plots
using LinearAlgebra
using ForwardDiff
using StatsFuns
using Optim

In [4]:
# generate synthetic data
Random.seed!(123)

# set parameters
n = 100
β = [0.1, 0.9]

# generate data
X = hcat(ones(n), randn(n, 1))

p = logistic.(X * β)
y = rand.(Bernoulli.(p));

logreg = SSM.BernoulliRegression()
SSM.fit!(logreg, reshape(X[:, 2], length(y), 1), y)

2-element Vector{Float64}:
 -0.2254724389883398
  1.1635789534220071

In [6]:
model = SSM.SwitchingBernoulliRegression(;K=2, λ=0.1)
SSM.fit!(model, reshape(X[:, 2], length(y), 1), y)

Log-Likelihood at iter 1: -60.63999840059348
Log-Likelihood at iter 2: -58.716157104346955
Log-Likelihood at iter 3: -58.65914431475913
Log-Likelihood at iter 4: -58.6334069835488
Log-Likelihood at iter 5: -58.621134223960375
Log-Likelihood at iter 6: -58.61466348073864
Log-Likelihood at iter 7: -58.61055306265681
Log-Likelihood at iter 8: -58.60738390190144
Log-Likelihood at iter 9: -58.60462866644438
Log-Likelihood at iter 10: -58.60212085969285
Log-Likelihood at iter 11: -58.599822807315974
Log-Likelihood at iter 12: -58.597731881580245
Log-Likelihood at iter 13: -58.59584712607942
Log-Likelihood at iter 14: -58.59416052827664
Log-Likelihood at iter 15: -58.59265722625968
Log-Likelihood at iter 16: -58.59131815054471
Log-Likelihood at iter 17: -58.59012266091704
Log-Likelihood at iter 18: -58.58905047266244
Log-Likelihood at iter 19: -58.5880828315609
Log-Likelihood at iter 20: -58.58720308597043
Log-Likelihood at iter 21: -58.58639686646999
Log-Likelihood at iter 22: -58.5856520147

101-element Vector{Float64}:
 -Inf
 -60.63999840059348
 -58.716157104346955
 -58.65914431475913
 -58.6334069835488
 -58.621134223960375
 -58.61466348073864
 -58.61055306265681
 -58.60738390190144
 -58.60462866644438
   ⋮
 -58.558901617604405
 -58.55861835016518
 -58.55833709753887
 -58.55805785917444
 -58.557780632262975
 -58.55750541473512
 -58.557232204206876
 -58.55696099769719
 -58.556691792127374

In [4]:
# synthetic poisson regression data
Random.seed!(123)

# set parameters
n = 100
β = [0.1, 0.9]
# generate data

X = hcat(ones(n), randn(n, 1))
λ = exp.(X * β)

y = rand.(Poisson.(λ))

poisreg = SSM.PoissonRegression()
SSM.fit!(poisreg, reshape(X[:, 2], length(y), 1), y)

2-element Vector{Float64}:
 0.17487914508365066
 0.947349969129698

In [5]:
model = SSM.SwitchingPoissonRegression(;K=2, λ=0.1)
fit!(model, reshape(X[:, 2], length(y), 1), y)

Log-Likelihood at iter 1: -1366.8846098062436
Log-Likelihood at iter 2: -135.4005597754357
Log-Likelihood at iter 3: -133.73068038694203
Log-Likelihood at iter 4: -133.61715276722063
Log-Likelihood at iter 5: -133.59051839050187
Log-Likelihood at iter 6: -133.58330861288943
Log-Likelihood at iter 7: -133.5810410876446
Log-Likelihood at iter 8: -133.58017212723954
Log-Likelihood at iter 9: -133.5797618109518
Log-Likelihood at iter 10: -133.57952850236128
Log-Likelihood at iter 11: -133.57937345116048
Log-Likelihood at iter 12: -133.57925635582475
Log-Likelihood at iter 13: -133.57915888360156
Log-Likelihood at iter 14: -133.57907217931108
Log-Likelihood at iter 15: -133.57899185289824
Log-Likelihood at iter 16: -133.57891571310367
Log-Likelihood at iter 17: -133.5788426697616
Log-Likelihood at iter 18: -133.5787721839067
Log-Likelihood at iter 19: -133.57870398970306
Log-Likelihood at iter 20: -133.5786379533523
Log-Likelihood at iter 21: -133.57857400248645
Log-Likelihood at iter 22: -

101-element Vector{Float64}:
   -Inf
 -1366.8846098062436
  -135.4005597754357
  -133.73068038694203
  -133.61715276722063
  -133.59051839050187
  -133.58330861288943
  -133.5810410876446
  -133.58017212723954
  -133.5797618109518
     ⋮
  -133.57696581957745
  -133.57696033195236
  -133.57695496669908
  -133.5769497182784
  -133.57694458137513
  -133.57693955095505
  -133.57693462220647
  -133.57692979048468
  -133.57692505142685